services:
  hkbus:
    image: hkbus
    container_name: hkbus
    hostname: hkbus
    restart: always
    build:
      context: ../
      dockerfile: ./Dockerfile
      args:
        CI: ${CI}
        NEXT_PUBLIC_OSM_PROVIDER_HOST: ${NEXT_PUBLIC_OSM_PROVIDER_HOST}
        NEXT_PUBLIC_OSM_PROVIDER_URL: ${NEXT_PUBLIC_OSM_PROVIDER_URL}
        NEXT_PUBLIC_OSM_PROVIDER_URL_DARK: ${NEXT_PUBLIC_OSM_PROVIDER_URL_DARK}
        NEXT_PUBLIC_CI_JOB_ID: ${NEXT_PUBLIC_CI_JOB_ID}
    tty: true
    environment:
      CI: ${CI}
      NEXT_PUBLIC_OSM_PROVIDER_HOST: ${NEXT_PUBLIC_OSM_PROVIDER_HOST}
      NEXT_PUBLIC_OSM_PROVIDER_URL: ${NEXT_PUBLIC_OSM_PROVIDER_URL}
      NEXT_PUBLIC_OSM_PROVIDER_URL_DARK: ${NEXT_PUBLIC_OSM_PROVIDER_URL_DARK}
      NEXT_PUBLIC_CI_JOB_ID: ${NEXT_PUBLIC_CI_JOB_ID}
    ports:
      - ${port}:80
    volumes:
      - ../src:/usr/src/app/src
      - ../public:/usr/src/app/public